version: 2
updates:
  - package-ecosystem: "git-submodule"
    directory: "/" # hoặc subfolder chứa submodule
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
