name: Build Eternal-Flame  # Tên của workflow, xuất hiện trong giao diện GitHub Actions

on:
  push:
    branches:
      - main  # Workflow sẽ chạy khi có commit được đẩy lên nhánh `main`

jobs:
  build:  # Định nghĩa công việc (job) tên là "build"
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu mới nhất

    steps:  # Các bước thực hiện trong job
      - name: Check out repository  # Bước 1: Lấy mã nguồn từ repository
        uses: actions/checkout@v4  # Sử dụng action có sẵn của GitHub để clone repository

      - name: Build Docker Image  # Bước 2: Tạo Docker image
        run: |
          docker build -t eternal-flame-unity:alpha .  # Build Docker image từ Dockerfile và đặt tên là `eternal-flame-unity:alpha`

      - name: Build Unity Project  # Bước 3: Sử dụng Docker container để build Unity project
        run: |
          docker run -v $(pwd):/project eternal-flame-unity:alpha \  # Mount thư mục hiện tại vào container (tại /project)
          /opt/Unity/Editor/Unity \                                  # Chạy Unity Editor CLI trong container
          -batchmode -nographics \                                   # Chế độ không hiển thị GUI
          -projectPath /project \                                    # Đường dẫn tới dự án Unity (đã mount)
          -buildTarget StandaloneWindows64 \                         # Build cho nền tảng Windows 64-bit
          -quit                                                     # Đóng Unity sau khi hoàn thành

      - name: Upload Build Artifacts  # Bước 4: Upload file build để lưu trữ và tải về sau
        uses: actions/upload-artifact@v4  # Sử dụng action có sẵn để upload artifacts
        with:
          name: EternalFlameBuild  # Tên artifact sau khi upload (hiển thị trên GitHub Actions)
          path: /project/Build/    # Đường dẫn tới thư mục chứa file build Unity (được Unity tạo ra)
